[package]
name = "rs_lib_serde_strategy "
version = "0.1.0"
authors = ["alexandre.mahdhaoui <alexandre.mahdhaoui@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.145", features = ["derive"]}

[dev-dependencies]
serde_json = "1.0.85"
pretty_assertions = "1"
